### ISSUE TITLE
'Uncaught ReferenceError: Intl is not defined' on Android browser version 4.0

### ISSUE THREAD

**Issue by khizar** [richardschneider/money-works#6]
Seems like the polyfill is not working. Can i confirm it somehow?

**Comment by khizar** [comment]
Ok so the polyfill is not shipped to the browser as it says in a code comment. Added a cdn link in my html to get it in the browser.

**Comment by richardschneider** [comment]
Is it now working?

**Comment by khizar** [comment]
Yup it is. Ill post if something goes wrong.
